<?php

declare(strict_types=1);

namespace app\tests\Unit\Models;

use app\models\Member;

final class MemberTest extends \Codeception\Test\Unit
{
    public function testEmailIsAutoGeneratedFromNameWhenEmpty(): void
    {
        $model = new Member();
        $model->nama = 'Budi Santoso';
        $model->email = '';

        $model->validate();

        verify($model->email)->equals('budi.santoso@gmail.com');
    }

    public function testEmailAddsGmailSuffixWhenLocalPartOnly(): void
    {
        $model = new Member();
        $model->nama = 'Budi Santoso';
        $model->email = 'budi.santoso';

        $model->validate();

        verify($model->email)->equals('budi.santoso@gmail.com');
    }
}
